# Gather facts in case gather_facts was set to 'no' in playbook.
- name: Gathering facts
  setup:

- include_tasks: apt.yml

- include_tasks: pip.yml
    
- include_tasks: ssh.yml

- include_tasks: sysctl.yml

- include_tasks: access.yml
    
- include_tasks: monit.yml
  when: not (slack_webhook == "")
