# Gather facts in case gather_facts was set to 'no' in playbook.
- name: Gathering facts
  setup:

- include: apt.yml

- include: pip.yml
    
- include: ssh.yml

- include: sysctl.yml

- include: access.yml
    
- include: monit.yml
  when: not (slack_webhook == "")
